= Chapter8
Firstname Lastname <author@asciidoctor.org>
3.0, July 29, 2022: AsciiDoc article template
:toc:
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/


== 1.프로그래밍 언어에서 변수를 사용하기 전에 변수를 선언해야 하는 이유는 무엇입니까? 이것이 정확성과 견고성과 어떤 관련이 있습니까?
====
프로그램 개발중 오해가 생기지 않기위해서.
====


== 2. 전제 조건 은 무엇입니까 ? 예를 들어보세요.
====
if(x.length!=0)
이조건이 일치해야만 실행되는것.
====

== 3.올바른 프로그램을 작성하는 데 전제 조건이 어떻게 도움이 될 수 있는지 설명하십시오.

====
전제조건을 사용함으로써 프로그램에 예상치못한 에러를 방지할수있다.
====

== 4.이진 검색 알고리즘의 while 루프 에 대한 유용한 루프 불변성을 찾습니다 ( 하위 섹션 7.5.1 ).

====
====

== 5.Java에는 Throwable 이라는 사전 정의된 클래스가 있습니다 . 이 클래스는 무엇을 나타냅니까? 왜 존재합니까?
====
예외상황가 에러등을 대비한 것들이 속해있다.
====

== 6.주어진 정수 N 에서 시작하여 3N+1 시퀀스를 인쇄하는 메서드를 작성하세요 . 시작 값은 메소드에 대한 매개변수여야 합니다. 매개변수가 0보다 작거나 같으면 IllegalArgumentException 이 발생합니다 . 시퀀스의 숫자가 너무 커서 int 유형의 값으로 표시할 수 없는 경우 ArithmeticException 이 발생합니다 .
====
static void printThreeNSequence(int N) {
if (N < 1) {
throw new IllegalArgumentException(
"Starting value for 3N+1 sequence must be > 0.");
}
System.out.println("3N+1 sequence starting from " + N + " is: ");
System.out.println(N);
while (N > 1) {
if (N % 2 == 0) {  // N is even.  Divide by 2.
N = N / 2;
}
else {  // N is odd.  Multiply by 3 and add 1.
if (N > 2147483646/3) {
throw new ArithmeticException("Value has exceeded the largest int.");
}
N = 3 * N + 1;
}
System.out.println(N);
}
}
====



== 7.오류를 확인하기 위해 예외 대신 Assert 문을 사용하여 이전 질문의 메서드를 다시 작성하세요 . 프로그램이 실행될 때 두 가지 버전의 메소드 간의 차이점은 무엇입니까?.code
[source,java]
----
static void printThreeNSequence(int N) {
   주장 N > 0 : "3N+1 시퀀스의 시작 값은 > 0이어야 합니다.";
   System.out.println("" + N + "에서 시작하는 3N+1 시퀀스는 다음과 같습니다: ");
   System.out.println(N);
   while (N > 1) {
      if (N % 2 == 0) { // N은 짝수입니다. 2로 나눕니다.
          N = N / 2;
      }
      else { // N은 홀수입니다. 3을 곱하고 1을 더합니다.
          Assert N <= 2147483646/3: "값이 가장 큰 정수를 초과했습니다.



      }
      System.out.println(N);
   }

}
----

== 8.일부 예외 클래스는 필수 예외 처리가 필요한 확인된 예외 입니다 . 이것이 무엇을 의미하는지 설명하세요.
====
Runtime Exception을 제외한 Exception은 플수적으로 thorws를 이용하여 예외해줘야한다.
====

== 9. 헤더가 있는 서브루틴 processData()를 고려해보세요.

정적 무효 processData()가 IOException을 발생시킵니다.
이 서브루틴을 호출하고 IOException 이 발생 하면 오류 메시지를 인쇄하는 try..catch 문을 작성하세요 .
====
try {
processData();
}
catch (IOException e) {
System.out.println("An IOException occurred while processing the data.");
}
====


== 10.서브루틴에서 오류가 발생할 때 왜 예외를 발생시켜야 합니까? 그냥 프로그램을 종료하면 안되나요?

====
프로그램이 예상치못하게 종료된다는것은 프로그램에 예상치못한 취약점을 일으킬수잇다.
====

== 11. 동일한 작업을 수행하는 두 가지 알고리즘 중 하나를 선택한다고 가정해 보겠습니다. 하나는 평균 사례 실행 시간이 Θ(n 2 )인 반면, 두 번째 알고리즘의 실행 시간은 Θ(n*log(n))인 평균 사례 실행 시간을 갖습니다. 크기 n = 100의 입력을 처리해야 한다고 가정합니다. 어떤 알고리즘을 선택하시겠습니까? 처리하려는 입력에 대해 가장 빠른 알고리즘을 선택하고 있다고 확신할 수 있습니까?

====
다른 정보가 없는 경우 런타임이 Θ(n*log(n))인 두 번째 알고리즘이 더 나은 선택입니다. 왜냐하면 대부분의 n 값에 대해 n*log(n)이 n 2 보다 훨씬 작기 때문 입니다
====

== 12. 다음 알고리즘의 실행 시간을 분석합니다. 즉, 알고리즘의 실행 시간이 O(f(n)) 또는 더 좋게는 Θ(f(n))이 되는 함수 f(n)을 찾습니다. A가 정수 배열이라고 가정 하고 배열의 길이를 입력 크기 n으로 사용합니다.

정수 총 = 0;
for (int i = 0; i < A.length; i++) {
if (A[i] > 0)
total = total + A[i];
}

====
이 알고리즘의 실행 시간은 Θ(n)입니다. 코드에는 n번 평가되는 여러 가지 항목이 있습니다. 즉, "i < A.length" 테스트, "i++" 증분, if 문의 테스트입니다. 초기화는 한 번 수행되며 n번 이상 실행되지 않습니다. 최악의 경우와 평균 경우의 실행 시간은 모두 Θ(n)입니다.

====